services:
  db:
    image: mysql:8.3
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "8092:3306"

  web:
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_DATABASE: test_database
      DB_PORT: 3306
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      DICE_MAX_NUMBER: 13
      RETURN_TO_PLAYER: 95 #percentage
    ports:
      - "8090:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: test_user
      PMA_PASSWORD: test_password
      UPLOAD_LIMIT: 50M
    ports:
      - "8091:80"
    depends_on:
      - db
